

class Clues:
    backboneClues = ["spine", "body", "calcium"]
    BagClues = []
    baguetteClue = []
    baldClue = []
    balloonClue = []
    bananaClue = []
    banisterClue = []
    baseballClue = []
    baseboardsClue = []
    basketballClue = []
    batClue = []
    batteryClue = []
    beachClue = []
    beanstalkClue = []
    bedbugClue = []
    beerClue = []
    beethovenClue = []
    beltClue = []
    bibClue = []
    bicycleClue = []
    bigClue = []
    bikeClue = []
    billboardClue = []
    birdClue = []
    birthdayClue = []
    biteClue = []
    blacksmithClue = []
    blanketClue = []
    bleachClue = []
    blimpClue = []
    blossomClue = []
    blueprintClue = []
    bluntClue = []
    blurClue = []
    boaClue = []
    boatClue = []
    bobClue = []
    bobsledClue = []
    bodyClue = []
    bombClue = []
    bonnetClue = []
    bookClue = []
    boothClue = []
    bowtieClue = []
    boxClue = []
    boyClue = []
    brainstormClue = []
    brandClue = []
    braveClue = []
    brideClue = []

    def __init__(self):
        pass