

class Deck:
    deckAndClues = {
        "backbone": ["spine", "body", "calcium"],
        "bag": ["container", "accessory,", "fashion"],
        "baguette": ["french","carbohydates","bakery"],
        "bald": ["smooth", "hairless", "shiny"],
        "balloon": ["helium","round","party"],
        "banana": ["fruit", "eat", "yellow", "plant"],
        "banister": ["railings", "stair", "home"],
        "baseball": ["sport","helmet", "exercise", "giants"],
        "baseboards": ["wall", "trimming", "architecture", "home"],
        "basketball": ["sport", "exercise", "equipment"],
        "bat": ["pitcher", "catcher", "animal"],
        "battery": ["energize", "power", "assault"],
        "beach": ["sand", "fun", "ocean", "wave", "sun", "warm"],
        "beanstalk": ["cultivate", "thin", "plant"],
        "bedbug": ["home", "small", "sleep", "home"],
        "beer": ["drink", "alcohol", "party"],
        "beethoven": ["composer", "piano", "music"],
        "belt": ["pants", "accessory", "fashion"],
        "bib": ["baby", "eat", "messy"],
        "bicycle": ["exercise", "wheel", "helmet"],
        "big": ["size", "giants", "small"],
        "bike": ["equipment", "wheel"],
        "billboard": ["advertisement", "large", "images"],
        "bird": ["animal", "flight", "feathers"],
        "birthday": ["party", "fun", "present"],
        "bite": ["eat","teeth", "chew"],
        "blacksmith": ["iron", "forge", "ironwork", "fire"],
        "blanket": ["warm", "quilt", "baby"],
        "bleach": ["toxic", "chemical", "white"],
        "blimp": ["ship", "float", "air", "fly"],
        "blossom": ["flower", "bud", "floral", "plant"],
        "blueprint": ["red", "architecture", "build", "building"],
        "blunt": ["dull", "honest"],
        "blur": ["fuzzy", "smear", "messy"],
        "boa": ["snake", "feathered", "scale"],
        "boat": ["float", "ship", "wave", "ocean"],
        "bob": ["bounce", "name", "float", "sport"],
        "bobsled": ["snow", "slide"],
        "body": ["flesh", "limb", "physical"],
        "bomb": ["explosion", "boom", "fire"],
        "bonnet": ["hat", "lace", "baby"],
        "book": ["paper", "reading", "tomb", "manual"],
        "booth": ["counter", "shop"],
        "bowtie": ["tuxedo", "silk", "fancy", "ceremony"],
        "box": ["cube", "square", "cardboard"],
        "boy": ["man", "girl"],
        "brainstorm": ["head", "thinking", "hurricane", "mind", "mindmap"],
        "brand": ["expensive", "burn", "label", "livestock", "fancy", "shop"],
        "brave": ["courageous", "courage", "hearty"],
        "bride": ["marry", "wedding", "dress", "veil", "marriage", "girl", "ceremony", "lace", "white"]
    }

    def __init__(self):
        pass
