

class Deck:
    deckAndClues = {
        "backbone": ["spine", "body", "calcium"],
        "bag": ["container", "accessory,", "fashion"],
        "baguette": ["french","carbohydates","bakery"],
        "bald": ["smooth", "hairless", "shiny"],
        "balloon": ["helium","round","party"],
        "banana": ["fruit", "eat", "yellow"],
        "banister": ["railings", "stair", "home"],
        "baseball": ["sport","helmet", "exercise"],
        "baseboards": ["wall", "trimming", "architecture"],
        "basketball": ["sport", "exercise", "equipment"],
        "bat": ["pitcher", "catcher", "animal"],
        "battery": ["energize", ],
        "beach": ["sand", "fun", ],
        "beanstalk": ["cultivate"],
        "bedbug": ["home", "small", "sleep"],
        "beer": ["drink",],
        "beethoven": ["composer", "piano", "music"],
        "belt": ["pants", "accessory", "fashion"],
        "bib": ["baby", "eat", "messy" ],
        "bicycle": ["exercise", "wheel", "helemet"],
        "big": ["size", ],
        "bike": ["equipment,"],
        "billboard": ["advertisement", "large", "images" ],
        "bird": ["animal", "flight", "feathers"],
        "birthday": ["party", "fun", "present"],
        "bite": ["eat","teeth", "chew"],
        "blacksmith": [],
        "blanket": [],
        "bleach": [],
        "blimp": [],
        "blossom": [],
        "blueprint": [],
        "blunt": [],
        "blur": [],
        "boa": [],
        "boat": [],
        "bob": [],
        "bobsled": [],
        "body": [],
        "bomb": [],
        "bonnet": [],
        "book": [],
        "booth": [],
        "bowtie": [],
        "box": [],
        "boy": [],
        "brainstorm": [],
        "brand": [],
        "brave": [],
        "bride": []
    }

    def __init__(self):
        pass
