

class Deck:
    deckAndClues = {
        "backbone": ["spine", "body", "calcium"],
        "bag": [],
        "baguette": [],
        "bald": [],
        "balloon": [],
        "banana": [],
        "banister": [],
        "baseball": [],
        "baseboards": [],
        "basketball": [],
        "bat": [],
        "battery": [],
        "beach": [],
        "beanstalk": [],
        "bedbug": [],
        "beer": [],
        "beethoven": [],
        "belt": [],
        "bib": [],
        "bicycle": [],
        "big": [],
        "bike": [],
        "billboard": [],
        "bird": [],
        "birthday": [],
        "bite": [],
        "blacksmith": [],
        "blanket": [],
        "bleach": [],
        "blimp": [],
        "blossom": [],
        "blueprint": [],
        "blunt": [],
        "blur": [],
        "boa": [],
        "boat": [],
        "bob": [],
        "bobsled": [],
        "body": [],
        "bomb": [],
        "bonnet": [],
        "book": [],
        "booth": [],
        "bowtie": [],
        "box": [],
        "boy": [],
        "brainstorm": [],
        "brand": [],
        "brave": [],
        "bride": []
    }

    def __init__(self):
        pass
